### ISSUE TITLE
Glasses Problems

### ISSUE THREAD

**Issue by rdephillip** [GMA950/esx_newaccessories#3]
Purchasing glasses returns a nil error in the console.

The K Menu and /glasses also returns a nil value.

It seems like the script is not passing the data to the datastore properly hence causing issues.

I am working on a copy to fix this for our server, and reported this on FiveM forums. Any news on how to fix this will be helpful.

**Comment by rdephillip** [comment]
So far I have written in code to remove the glasses and add them back that is aligned with the shoes code. It isn't necessarily using the accessories script but this script on purchase or item toggle is feeding esx_datastore a nil value. I will continue to debug and work to identify and resolve the issue I'm seeing.

**Comment by iSentrie** [comment]
![image](https://user-images.githubusercontent.com/29688478/78015822-9d317c80-7352-11ea-8818-0d8a414b3a44.png)
This comes for all accessories for me.
When trying to /glasses /mask, etc..

This for /mask
![image](https://user-images.githubusercontent.com/29688478/78015970-d669ec80-7352-11ea-8133-e7f83ae4bb3b.png)

This for glasses
![image](https://user-images.githubusercontent.com/29688478/78016211-2d6fc180-7353-11ea-89a7-c359c94f01e3.png)
First error before purchase, second after purchase and both times using /glasses

**Comment by iSentrie** [comment]
So esx_newaccessories throws error here:

```
ESX.RegisterServerCallback('esx_newaccessories:get', function(source, cb, accessory)
	local xPlayer = ESX.GetPlayerFromId(source)

	TriggerEvent('esx_datastore:getDataStore', 'user_' .. string.lower(accessory), xPlayer.identifier, function(store)
		local hasAccessory = (store.get('has' .. accessory) and store.get('has' .. accessory) or false)
		local skin = (store.get('skin') and store.get('skin') or {})

		cb(hasAccessory, skin)
	end)

end)
```

Says this line
`TriggerEvent('esx_datastore:getDataStore', 'user_' .. string.lower(accessory), xPlayer.identifier, function(store)`

and xPlayer returns
![image](https://user-images.githubusercontent.com/29688478/78016752-e6360080-7353-11ea-8e28-e9074e2a6266.png)
but xPlayer.identifier returns a correct gta license, so probably issue is not here...

....

Just noticed that when u buy glasses it throws error
![image](https://user-images.githubusercontent.com/29688478/78017354-d36ffb80-7354-11ea-9ef7-de6d1dc05e15.png)

Which also returns correct identifier.. Then what's wrong...?

`	TriggerEvent('esx_datastore:getDataStore', 'user_' .. string.lower(accessory), xPlayer.identifier, function(store)`

Ok so this ^ have these returns

> 	print(xPlayer.identifier) = correct
> 	print(user_glasses) = nil
> 	print(user_) = nil
> 	print(accessory) = Glasses

Someone teach me how to troubleshoot, lol.
So since there was 2 nil, i went checking my database, i found that there is nothing in 'datastore' declared, i added user_glasses, how the hell i could miss this, lol, now this:
![image](https://user-images.githubusercontent.com/29688478/78018701-0adfa780-7357-11ea-9430-f03e441a604f.png)
Which is obviously this

> local hasAccessory = (store.get('has' .. accessory) and store.get('has' .. accessory) or false)

Who the hell is 'store'???

### Ok done looks like it's fixed. Was missing DB, oh my....
**RIP**

**Comment by rdephillip** [comment]
@XvenDeR I apologize for not interacting while you troubleshot this. I was assigned to move on to more important scripts on the server and then eventually tasked to developing a custom server management discord bot.

What was missing here?  The store table? or is it misnamed?.... is store supposed to be datastore?

**Comment by iSentrie** [comment]
> @XvenDeR I apologize for not interacting while you troubleshot this. I was assigned to move on to more important scripts on the server and then eventually tasked to developing a custom server management discord bot.
> 
> What was missing here? The store table? or is it misnamed?.... is store supposed to be datastore?

probably just forgot to import database, since im working on few servers and most of them already had imported basic sqls, so probably just sql import was missing at my case at that time.

**Comment by rdephillip** [comment]
I suspect this servers original dev effed up the code. I actually deleted the mod and freshly downloaded and setup the mod and it works out of the box fine now.

I just wanted to make certain there wasn't something else. Thank you @XvenDeR
